app:
  name: &app_name go-college
  version: 1.0.0
  environment: development
  shutdown_timeout: 5s

http:
  server:
    app_name: *app_name
    mode: debug
    port: 8181
    write_timeout: 10s
    read_timeout: 10s
    idle_timeout: 60s
    max_body_bytes: 1048576
  metrics_server:
    mode: release # debug, release
    port: 9191
    write_timeout: 10s
    read_timeout: 10s
    idle_timeout: 60s
    max_body_bytes: 1048576 # 1MB
  client:
    enabled: true
    max_idle_conns: 100
    max_idle_conns_per_host: 10
    max_conns_per_host: 20
    idle_conn_timeout: 90s
    dial_timeout: 30s
    keep_alive: 30s
    tls_handshake_timeout: 10s
    response_header_timeout: 10s
    expect_continue_timeout: 1s
    disable_compression: false
    timeout: 10s
    circuit_breaker:
      max_retries: 2
      backoff_min: 100ms
      backoff_max: 2s

database: # postgres, mysql, oracle
  postgres:
    enabled: true
    driver: postgres
    host: ${POSTGRES_HOST}
    port: 5432
    user: postgres
    password: ${POSTGRES_DOCKER_PASSWORD}
    dbname: go_college
    sslmode: false
    max_conns: 25
    min_conns: 5
    conn_max_lifetime: 1h
    conn_max_idle_time: 30m

logger:
  enabled: true
  level: debug # debug, info, warn, error
  format: json # json, console
  output: stdout # stdout, file
  path: ./logs/app.log
  max_size: 100 # megabytes
  max_backups: 7
  max_age: 30 # days
  compress: true # disabled by default

middleware:
  public_paths:
    - /debug/*
    - /favicon.ico

queries:
  path: ./configs/queries/

tracer:
  enabled: true
  endpoint: ${TRACER_HOST}:4317
  protocol: grpc

metric:
  enabled: true
